#!/usr/bin/env bash
# vnu (Nu HTML Checker) over every repo-owned HTML file, including embedded
# CSS in <style> blocks (--also-check-css).
#
# Covers all *.html under the repo (currently src/server/webui/* and
# docs/provenance.html); fetched third-party packages (zig-pkg, node_modules)
# and dot-directories (.git, caches) are excluded. The inline <script> JS is
# generated by scripts/build-webui-ts.sh from TypeScript that
# scripts/lint-webui.sh type-checks (tsc) and lints (oxlint), so it is not
# re-checked here.
#
# vnu runs through bunx pinned by VNU_VERSION, the same convention as oxlint
# (the repo does not track package.json / node_modules; see .gitignore
# "opencode tooling only"). vnu-jar is a Java tool, so java is required.
# Override locally: VNU_VERSION=26.8.20 bash scripts/lint-html.sh
#
# vnu-filter.txt drops the deliberate hx-* mini-htmx attributes; any other
# vnu error fails the gate. Warnings do not fail (vnu reserves warnings for
# ARIA/style hints with false-positive potential); errors are strict.

set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
vnu_version="${VNU_VERSION:-26.8.20}"

mapfile -t html_files < <(
  find "$root" -name '*.html' \
    -not -path '*/.*' \
    -not -path '*/node_modules/*' \
    -not -path '*/zig-pkg/*' \
    -not -path '*/zig-out/*' \
    | sort
)

if [ "${#html_files[@]}" -eq 0 ]; then
  echo "zdtd: lint-html: no HTML files found under $root" >&2
  exit 1
fi

bunx "vnu-jar@$vnu_version" --filterfile "$root/vnu-filter.txt" --also-check-css "${html_files[@]}"
