//! Stock sandbox value-set and option tables, generated from
//! `../7dtd-engine-research/tools/sandbox/sandbox_tables.json` by
//! `../7dtd-engine-research/tools/sandbox/gen_zig_tables.py` (do not hand-edit).
//! Source of truth: `SandboxOptionManager.SetupOptions` IL of the stock
//! V3.1.0 b14 dedicated server (docs/sandbox-options.md §2.1/§3 in the
//! 7dtd-engine-research repo). Decode contract: code := 'A' + 3-letter groups
//! (2-letter base-26 option id + 1-letter value-set index).

pub const Kind = enum(u8) { float, int, boolean };

pub const ValueSet = struct {
    name: []const u8,
    kind: Kind,
    floats: []const f32,
    ints: []const i32,
};

pub const Option = struct {
    /// SandboxOptions enum value (wire-stable; the codec addresses options by it).
    id: u16,
    /// SandboxOptions enum member name.
    name: []const u8,
    set_name: []const u8,
    kind: Kind,
    default_f: f32,
    default_i: i32,
};

/// All 65 value sets (stock data).
pub const value_sets = [_]ValueSet{
    .{ .name = "AISmellMode", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5 } },
    .{ .name = "AirDropRandomTime", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5, 6 } },
    .{ .name = "AirDrops", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5, 6 } },
    .{ .name = "ApiaryInput", .kind = .float, .floats = &.{ 0.0, 0.2, 0.4, 0.6, 0.8, 1.0, 1.5, 2.0, 3.0 }, .ints = &.{} },
    .{ .name = "BackpackCrafting", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3 } },
    .{ .name = "BarterValues", .kind = .float, .floats = &.{ 0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 3.0, 4.0 }, .ints = &.{} },
    .{ .name = "BiomeEnemyDensity", .kind = .int, .floats = &.{}, .ints = &.{ -1, 0, 1, 2, 3, 4, 5 } },
    .{ .name = "BloodMoonCount", .kind = .int, .floats = &.{}, .ints = &.{ 4, 6, 8, 10, 12, 16, 24, 32, 64 } },
    .{ .name = "BloodMoonFrequency", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 14, 20, 30 } },
    .{ .name = "BloodMoonRange", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 7, 10, 14, 20 } },
    .{ .name = "BloodMoonWarning", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2 } },
    .{ .name = "Celebrate", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2 } },
    .{ .name = "CollectorOutput", .kind = .float, .floats = &.{ 1.0, 2.0, 3.0, 4.0, 5.0 }, .ints = &.{} },
    .{ .name = "CropGrowthSpeed", .kind = .float, .floats = &.{ 1000.0, 0.0, 0.2, 0.5, 0.75, 1.0, 1.5, 2.0, 3.0 }, .ints = &.{} },
    .{ .name = "DamageValues", .kind = .float, .floats = &.{ 0.0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1.0, 1.25, 1.5, 2.0, 2.5, 3.0 }, .ints = &.{} },
    .{ .name = "DamageValuesNoNone", .kind = .float, .floats = &.{ 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1.0, 1.25, 1.5, 2.0, 2.5, 3.0 }, .ints = &.{} },
    .{ .name = "DayLightLength", .kind = .int, .floats = &.{}, .ints = &.{ 0, 4, 6, 8, 10, 12, 14, 16, 18, 20, 24 } },
    .{ .name = "DayNightLength", .kind = .int, .floats = &.{}, .ints = &.{ 10, 20, 30, 40, 50, 60, 90, 120 } },
    .{ .name = "DeathPenalty", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3 } },
    .{ .name = "DegradeItemsOnDeath", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3 } },
    .{ .name = "DewCollectorInput", .kind = .float, .floats = &.{ 0.0, 1.0, 2.0, 3.0 }, .ints = &.{} },
    .{ .name = "DisabledLowDefaultHigh", .kind = .float, .floats = &.{ 0.0, 0.25, 0.5, 1.0, 1.5, 2.0 }, .ints = &.{} },
    .{ .name = "DropOnDeath", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5, 6 } },
    .{ .name = "DropOnQuit", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5 } },
    .{ .name = "Encumbrance", .kind = .float, .floats = &.{ 10.0, 1.35, 1.0, 0.7, 0.35, 0.0 }, .ints = &.{} },
    .{ .name = "FullChickenStressEvent", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5 } },
    .{ .name = "Gravity", .kind = .float, .floats = &.{ 0.5, 0.6, 0.7, 0.8, 0.9, 1.0 }, .ints = &.{} },
    .{ .name = "HeadshotMode", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2 } },
    .{ .name = "ItemTierOptions", .kind = .int, .floats = &.{}, .ints = &.{ 1, 2, 3, 4, 5, 6 } },
    .{ .name = "JarRefund", .kind = .float, .floats = &.{ 0.0, 0.05, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0 }, .ints = &.{} },
    .{ .name = "JumpStrength", .kind = .float, .floats = &.{ 0.0, 0.5, 1.0, 1.25, 1.5, 2.0, 3.0 }, .ints = &.{} },
    .{ .name = "LootAbundanceValues", .kind = .float, .floats = &.{ 0.0, 0.25, 0.35, 0.5, 0.65, 0.75, 0.85, 1.0, 1.25, 1.5, 2.0, 3.0, 4.0, 5.0 }, .ints = &.{} },
    .{ .name = "LootRespawnDays", .kind = .int, .floats = &.{}, .ints = &.{ -1, 5, 7, 10, 15, 20, 30, 40, 50 } },
    .{ .name = "LoseItemCount", .kind = .int, .floats = &.{}, .ints = &.{ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 } },
    .{ .name = "LoseItemsOnDeathType", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5 } },
    .{ .name = "LowDefaultHigh", .kind = .float, .floats = &.{ 0.25, 0.5, 1.0, 1.5, 2.0 }, .ints = &.{} },
    .{ .name = "MaxChunkAge", .kind = .int, .floats = &.{}, .ints = &.{ -1, 1, 3, 5, 7, 10, 20, 30, 40, 50, 75, 100 } },
    .{ .name = "MaxDegradationAmounts", .kind = .float, .floats = &.{ 0.0, 0.05, 0.1, 0.15, 0.2, 0.25 }, .ints = &.{} },
    .{ .name = "MaxEnemyType", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5 } },
    .{ .name = "MaxStackSize", .kind = .float, .floats = &.{ 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 2.5, 3.0, 4.0, 5.0 }, .ints = &.{} },
    .{ .name = "MaxTechType", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4 } },
    .{ .name = "PlayerSpeedValues", .kind = .float, .floats = &.{ 0.0, 0.25, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 2.0, 3.0 }, .ints = &.{} },
    .{ .name = "PlayerSpeedValuesWithNone", .kind = .float, .floats = &.{ 0.25, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 2.0, 3.0 }, .ints = &.{} },
    .{ .name = "PointsPer", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5, 6, 7 } },
    .{ .name = "QuestPerDay", .kind = .int, .floats = &.{}, .ints = &.{ -1, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 } },
    .{ .name = "QuestPerTier", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15 } },
    .{ .name = "RepairTypes", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3 } },
    .{ .name = "ShowLocationTypes", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2 } },
    .{ .name = "ShowXP", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3 } },
    .{ .name = "SkillGainRate", .kind = .int, .floats = &.{}, .ints = &.{ 1, 2, 3, 4, 5 } },
    .{ .name = "SlowToFast", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5 } },
    .{ .name = "SmeltingType", .kind = .boolean, .floats = &.{}, .ints = &.{} },
    .{ .name = "SpeedValues", .kind = .float, .floats = &.{ 0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0, 3.0 }, .ints = &.{} },
    .{ .name = "StaminaRegen", .kind = .float, .floats = &.{ 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 2.0, 3.0 }, .ints = &.{} },
    .{ .name = "StaminaUsage", .kind = .float, .floats = &.{ 0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0 }, .ints = &.{} },
    .{ .name = "StarterSkillPoints", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 } },
    .{ .name = "StormFrequency", .kind = .float, .floats = &.{ 0.0, 0.5, 1.0, 1.5, 2.0, 3.0, 4.0, 5.0 }, .ints = &.{} },
    .{ .name = "TraderArea", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2 } },
    .{ .name = "TraderHourPresets", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4, 5, 6 } },
    .{ .name = "TraderResetInterval", .kind = .int, .floats = &.{}, .ints = &.{ -1, 1, 2, 3, 4, 5, 6, 7, 14 } },
    .{ .name = "XPGain", .kind = .float, .floats = &.{ 0.0, 0.25, 0.5, 0.75, 1.0, 1.25, 1.5, 1.75, 2.0, 3.0, 5.0 }, .ints = &.{} },
    .{ .name = "YesNo", .kind = .boolean, .floats = &.{}, .ints = &.{} },
    .{ .name = "ZombieFeralSense", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3 } },
    .{ .name = "ZombieRageChance", .kind = .float, .floats = &.{ 0.0, 0.15, 0.3, 0.35, 0.4, 0.5, 0.6, 0.75, 0.9, 1.0 }, .ints = &.{} },
    .{ .name = "ZombieSpeeds", .kind = .int, .floats = &.{}, .ints = &.{ 0, 1, 2, 3, 4 } },
};

/// All 165 options, in id order (stock data).
pub const options = [_]Option{
    .{ .id = 0, .name = "RangedDamage", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 1, .name = "MeleeDamage", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 2, .name = "BlockDamage", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 3, .name = "TerrainDamage", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 4, .name = "HeadshotMultiplier", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 5, .name = "CrouchSpeed", .set_name = "PlayerSpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 6, .name = "WalkSpeed", .set_name = "PlayerSpeedValuesWithNone", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 7, .name = "RunSpeed", .set_name = "PlayerSpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 8, .name = "JumpStrength", .set_name = "JumpStrength", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 9, .name = "StaminaUsage", .set_name = "StaminaUsage", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 10, .name = "StaminaRegen", .set_name = "StaminaRegen", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 11, .name = "PlayerLevelBonusApplied", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 12, .name = "JarRefund", .set_name = "JarRefund", .kind = .float, .default_f = 0.6, .default_i = 0 },
    .{ .id = 13, .name = "ShowHealthBars", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 14, .name = "ShowEnemyDamage", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 15, .name = "NewbieCoat", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 16, .name = "HeadshotMode", .set_name = "HeadshotMode", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 17, .name = "IncomingDamage", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 18, .name = "XPMultiplier", .set_name = "XPGain", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 19, .name = "ShowXP", .set_name = "ShowXP", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 20, .name = "EncumbranceModifier", .set_name = "Encumbrance", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 21, .name = "ItemDegradation", .set_name = "DisabledLowDefaultHigh", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 22, .name = "LoseItemsOnDeathType", .set_name = "LoseItemsOnDeathType", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 23, .name = "LoseItemsOnDeathCount", .set_name = "LoseItemCount", .kind = .int, .default_f = 0.0, .default_i = 1 },
    .{ .id = 24, .name = "DegradeItemsOnDeath", .set_name = "DegradeItemsOnDeath", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 25, .name = "DegradeAmountOnDeath", .set_name = "MaxDegradationAmounts", .kind = .float, .default_f = 0.1, .default_i = 0 },
    .{ .id = 26, .name = "DeathPenalty", .set_name = "DeathPenalty", .kind = .int, .default_f = 0.0, .default_i = 1 },
    .{ .id = 27, .name = "DropOnDeath", .set_name = "DropOnDeath", .kind = .int, .default_f = 0.0, .default_i = 1 },
    .{ .id = 28, .name = "DropOnQuit", .set_name = "DropOnQuit", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 29, .name = "InfectionRate", .set_name = "SpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 30, .name = "EnemySpawnMode", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 31, .name = "EntityDamage", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 32, .name = "BlockDamageAI", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 33, .name = "BlockDamageAIBM", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 34, .name = "ZombieMove", .set_name = "ZombieSpeeds", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 35, .name = "ZombieMoveNight", .set_name = "ZombieSpeeds", .kind = .int, .default_f = 0.0, .default_i = 3 },
    .{ .id = 36, .name = "ZombieFeralMove", .set_name = "ZombieSpeeds", .kind = .int, .default_f = 0.0, .default_i = 3 },
    .{ .id = 37, .name = "ZombieBMMove", .set_name = "ZombieSpeeds", .kind = .int, .default_f = 0.0, .default_i = 3 },
    .{ .id = 38, .name = "ZombieFeralSense", .set_name = "ZombieFeralSense", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 39, .name = "AISmellMode", .set_name = "AISmellMode", .kind = .int, .default_f = 0.0, .default_i = 3 },
    .{ .id = 40, .name = "AllowZombieDigging", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 41, .name = "ZombieRageChance", .set_name = "ZombieRageChance", .kind = .float, .default_f = 0.15, .default_i = 0 },
    .{ .id = 42, .name = "EntityIncomingDamage", .set_name = "DamageValuesNoNone", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 43, .name = "MaxEnemyTier", .set_name = "MaxEnemyType", .kind = .int, .default_f = 0.0, .default_i = 5 },
    .{ .id = 44, .name = "BiomeDayZombieRespawn", .set_name = "SlowToFast", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 45, .name = "BiomeDayAnimalRespawn", .set_name = "SlowToFast", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 46, .name = "BiomeDayEnemyDensity", .set_name = "BiomeEnemyDensity", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 47, .name = "ZombiesEatAnimals", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 48, .name = "BloodMoonFrequency", .set_name = "BloodMoonFrequency", .kind = .int, .default_f = 0.0, .default_i = 7 },
    .{ .id = 49, .name = "BloodMoonRange", .set_name = "BloodMoonRange", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 50, .name = "BloodMoonWarning", .set_name = "BloodMoonWarning", .kind = .int, .default_f = 0.0, .default_i = 1 },
    .{ .id = 51, .name = "BloodMoonEnemyCount", .set_name = "BloodMoonCount", .kind = .int, .default_f = 0.0, .default_i = 8 },
    .{ .id = 52, .name = "AirDropFrequency", .set_name = "AirDrops", .kind = .int, .default_f = 0.0, .default_i = 3 },
    .{ .id = 53, .name = "AirDropMarker", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 54, .name = "AirDropRandomTime", .set_name = "AirDropRandomTime", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 55, .name = "BiomeProgression", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 56, .name = "TemperatureSurvival", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 57, .name = "StormFreq", .set_name = "StormFrequency", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 58, .name = "StormWarning", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 59, .name = "HeatMapSensitivity", .set_name = "DisabledLowDefaultHigh", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 60, .name = "GlobalGSModifier", .set_name = "LowDefaultHigh", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 61, .name = "BiomeGSModifier", .set_name = "LowDefaultHigh", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 62, .name = "GlobalLSModifier", .set_name = "LowDefaultHigh", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 63, .name = "BiomeLSModifier", .set_name = "LowDefaultHigh", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 64, .name = "POITierLSModifier", .set_name = "LowDefaultHigh", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 65, .name = "GlobalTSModifier", .set_name = "LowDefaultHigh", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 66, .name = "DayNightLength", .set_name = "DayNightLength", .kind = .int, .default_f = 0.0, .default_i = 60 },
    .{ .id = 67, .name = "DayLightLength", .set_name = "DayLightLength", .kind = .int, .default_f = 0.0, .default_i = 18 },
    .{ .id = 68, .name = "AllowMap", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 69, .name = "AllowCompass", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 70, .name = "AllowScreenMarkers", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 71, .name = "ShowLocationInfo", .set_name = "ShowLocationTypes", .kind = .int, .default_f = 0.0, .default_i = 1 },
    .{ .id = 72, .name = "ShowDayTime", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 73, .name = "WorkstationsInTheWild", .set_name = "JarRefund", .kind = .float, .default_f = 0.0, .default_i = 0 },
    .{ .id = 74, .name = "MaxTechType", .set_name = "MaxTechType", .kind = .int, .default_f = 0.0, .default_i = 4 },
    .{ .id = 75, .name = "LootRespawnDays", .set_name = "LootRespawnDays", .kind = .int, .default_f = 0.0, .default_i = 7 },
    .{ .id = 76, .name = "LootTimer", .set_name = "SpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 77, .name = "LootMaxTier", .set_name = "ItemTierOptions", .kind = .int, .default_f = 0.0, .default_i = 6 },
    .{ .id = 78, .name = "GlobalLootCount", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 79, .name = "FoodLootCount", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 80, .name = "DrinkLootCount", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 81, .name = "MedicalLootCount", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 82, .name = "AmmoLootCount", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 83, .name = "ResourceLootCount", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 84, .name = "ArmorLootCount", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 85, .name = "MeleeLootCount", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 86, .name = "RangedLootCount", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 87, .name = "DukesLootCount", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 88, .name = "CraftingMagazinesLootCount", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 89, .name = "TreasureMapChance", .set_name = "PlayerSpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 90, .name = "LootBagChance", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 91, .name = "CropOutput", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 92, .name = "SeedDropOutput", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 93, .name = "CropGrowthSpeed", .set_name = "CropGrowthSpeed", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 94, .name = "BackpackCrafting", .set_name = "BackpackCrafting", .kind = .int, .default_f = 0.0, .default_i = 1 },
    .{ .id = 95, .name = "WorkstationCrafting", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 96, .name = "CraftingProgression", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 97, .name = "CraftingTime", .set_name = "SpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 98, .name = "CraftingInput", .set_name = "SpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 99, .name = "CraftingOutput", .set_name = "StaminaRegen", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 100, .name = "CraftingMaxTier", .set_name = "ItemTierOptions", .kind = .int, .default_f = 0.0, .default_i = 6 },
    .{ .id = 101, .name = "MiningOutput", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 102, .name = "HarvestingOutput", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 103, .name = "ScrappingOutput", .set_name = "SpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 104, .name = "SmeltingType", .set_name = "SmeltingType", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 105, .name = "DewCollectorTime", .set_name = "SpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 106, .name = "DewCollectorOutput", .set_name = "CollectorOutput", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 107, .name = "DewCollectorInput", .set_name = "DewCollectorInput", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 108, .name = "ApiaryTime", .set_name = "SpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 109, .name = "ApiaryOutput", .set_name = "CollectorOutput", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 110, .name = "ApiaryInput", .set_name = "ApiaryInput", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 111, .name = "BookLootCount", .set_name = "LootAbundanceValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 112, .name = "CrouchRunSpeed", .set_name = "PlayerSpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 113, .name = "RepairTypes", .set_name = "RepairTypes", .kind = .int, .default_f = 0.0, .default_i = 3 },
    .{ .id = 114, .name = "MaxDegradationAmount", .set_name = "MaxDegradationAmounts", .kind = .float, .default_f = 0.0, .default_i = 0 },
    .{ .id = 115, .name = "PointsPerMagazine", .set_name = "PointsPer", .kind = .int, .default_f = 0.0, .default_i = 1 },
    .{ .id = 116, .name = "SkillGainRate", .set_name = "SkillGainRate", .kind = .int, .default_f = 0.0, .default_i = 1 },
    .{ .id = 117, .name = "SkillPointsPerLevel", .set_name = "PointsPer", .kind = .int, .default_f = 0.0, .default_i = 1 },
    .{ .id = 118, .name = "QuestsEnabled", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 119, .name = "IntroQuestEnabled", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 120, .name = "TraderToTraderQuestsEnabled", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 121, .name = "StarterSkillPoints", .set_name = "StarterSkillPoints", .kind = .int, .default_f = 0.0, .default_i = 4 },
    .{ .id = 122, .name = "QuestsPerTier", .set_name = "QuestPerTier", .kind = .int, .default_f = 0.0, .default_i = 10 },
    .{ .id = 123, .name = "QuestProgressionDailyLimit", .set_name = "QuestPerDay", .kind = .int, .default_f = 0.0, .default_i = 4 },
    .{ .id = 124, .name = "BuriedQuestsEnabled", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 125, .name = "POIQuestsEnabled", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 126, .name = "TraderDialog", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 127, .name = "TraderHours", .set_name = "TraderHourPresets", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 128, .name = "TradersEnabled", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 129, .name = "VendingEnabled", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 130, .name = "TraderSellPrices", .set_name = "BarterValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 131, .name = "TraderBuyPrices", .set_name = "BarterValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 132, .name = "TraderProtection", .set_name = "TraderArea", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 133, .name = "TraderResetInterval", .set_name = "TraderResetInterval", .kind = .int, .default_f = 0.0, .default_i = -1 },
    .{ .id = 134, .name = "TraderItemAbundance", .set_name = "LowDefaultHigh", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 135, .name = "TraderBuyLimit", .set_name = "StarterSkillPoints", .kind = .int, .default_f = 0.0, .default_i = 3 },
    .{ .id = 136, .name = "TraderMaxTier", .set_name = "ItemTierOptions", .kind = .int, .default_f = 0.0, .default_i = 6 },
    .{ .id = 137, .name = "VendingResetInterval", .set_name = "TraderResetInterval", .kind = .int, .default_f = 0.0, .default_i = -1 },
    .{ .id = 138, .name = "VendingItemAbundance", .set_name = "LowDefaultHigh", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 139, .name = "ChallengesEnabled", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 140, .name = "IntroChallengesEnabled", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 141, .name = "VehicleFuelUsage", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 142, .name = "VehicleEntityDamage", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 143, .name = "VehicleBlockDamage", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 144, .name = "VehicleSelfDamage", .set_name = "DamageValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 145, .name = "ElectricalOutput", .set_name = "StaminaRegen", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 146, .name = "SillyCelebrate", .set_name = "Celebrate", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 147, .name = "SillyBigHeads", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 148, .name = "SillyTinyZombies", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 149, .name = "SillySounds", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 150, .name = "SillyLowGravity", .set_name = "Gravity", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 151, .name = "SillyBlackandWhite", .set_name = "YesNo", .kind = .boolean, .default_f = 0.0, .default_i = 0 },
    .{ .id = 152, .name = "ChickenCoopTime", .set_name = "SpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 153, .name = "ChickenCoopOutput", .set_name = "CollectorOutput", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 154, .name = "ChickenCoopInput", .set_name = "ApiaryInput", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 155, .name = "BiomeDayAnimalDensity", .set_name = "BiomeEnemyDensity", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 156, .name = "BiomeNightZombieRespawn", .set_name = "SlowToFast", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 157, .name = "BiomeNightAnimalRespawn", .set_name = "SlowToFast", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 158, .name = "BiomeNightEnemyDensity", .set_name = "BiomeEnemyDensity", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 159, .name = "BiomeNightAnimalDensity", .set_name = "BiomeEnemyDensity", .kind = .int, .default_f = 0.0, .default_i = 0 },
    .{ .id = 160, .name = "InfectionChance", .set_name = "SpeedValues", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 161, .name = "HungerMultiplier", .set_name = "StaminaUsage", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 162, .name = "ThirstMultiplier", .set_name = "StaminaUsage", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 163, .name = "StackSizeMultiplier", .set_name = "MaxStackSize", .kind = .float, .default_f = 1.0, .default_i = 0 },
    .{ .id = 164, .name = "FullChickenStressEvent", .set_name = "FullChickenStressEvent", .kind = .int, .default_f = 0.0, .default_i = 1 },
};
