#!/usr/bin/env python3
"""Generate the reference catalogs under docs/catalogs/ from source.

Every row is parsed from the declaration that owns it and carries a `file:line`
citation, so the catalogs cannot drift into hand-written inventories. Four pages:

    config.md        serverconfig.xml keys, zdtd.toml sections, sim rule groups
    admin-verbs.md   admin TCP commands, console verbs, bot verbs, host verbs
    save-formats.md  on-disk format magics, their enclosing function, their file
    module-graph.md  package-to-package @import edges and the enforced edge rules

Usage:
    python3 tools/gen_docs_catalogs.py           regenerate the pages
    python3 tools/gen_docs_catalogs.py --check   exit 1 when a page is stale

The parser is deliberately conservative: it recognises the declaration styles
used in this repository (module-level `pub const X = struct { ... };` and
`pub const X = union(enum) { ... };`) and reports nothing rather than guessing.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "catalogs"

BANNER = (
    "<!-- Generated by tools/gen_docs_catalogs.py - do not edit by hand. "
    "Run `make docs-catalogs` to regenerate. -->\n"
)

FIELD_RE = re.compile(r"^ {4}([a-z_][A-Za-z0-9_]*):\s*(.*?)(?:\s*=\s*(.*?))?,\s*$")
VARIANT_RE = re.compile(r"^ {4}([a-z_][A-Za-z0-9_]*)(?::\s*(.*?))?,\s*$")
DOC_RE = re.compile(r"^\s*///(.*)$")

# Upper-case literals that are not on-disk format magics.
MAGIC_DENYLIST = {"EOS", "NOPE"}

SAVE_SCAN = (
    "src/server/persist.zig",
    "src/server/game/clock_persist.zig",
    "src/server/game/bans.zig",
    "src/server/ally.zig",
    "src/world/store.zig",
    "src/world/chunk_flush.zig",
    "src/world/containers.zig",
    "src/world/signs.zig",
    "src/world/vending.zig",
    "src/world/workstations.zig",
    "src/world/light_te.zig",
)


def read(rel: str) -> list[str]:
    return (ROOT / rel).read_text(encoding="utf-8", errors="replace").splitlines()


def cell(value: str) -> str:
    return value.replace("|", "\\|").strip()


def body_of(rel: str, declaration: str) -> tuple[list[str], int]:
    """Lines inside `pub const <declaration> = ... {` up to its closing brace."""
    src = read(rel)
    start = None
    for index, line in enumerate(src):
        if line.startswith(f"pub const {declaration} = ") and line.rstrip().endswith("{"):
            start = index
            break
    if start is None:
        return [], 0
    depth = 0
    body = []
    for index in range(start, len(src)):
        depth += src[index].count("{") - src[index].count("}")
        if index > start:
            body.append(src[index])
        if depth <= 0 and index > start:
            body.pop()
            break
    return body, start + 2  # 1-based line of the first body line


def fields_of(rel: str, declaration: str) -> list[dict]:
    body, first_line = body_of(rel, declaration)
    rows = []
    pending: list[str] = []
    for offset, line in enumerate(body):
        doc = DOC_RE.match(line)
        if doc:
            pending.append(doc.group(1).strip())
            continue
        if not line.strip() or line.strip().startswith("//"):
            continue
        match = FIELD_RE.match(line)
        if match:
            rows.append(
                {
                    "name": match.group(1),
                    "type": (match.group(2) or "").strip(),
                    "default": (match.group(3) or "").strip() or "-",
                    "doc": " ".join(pending).strip() or "-",
                    "line": first_line + offset,
                }
            )
        pending = []
    return rows


def variants_of(rel: str, declaration: str) -> list[dict]:
    body, first_line = body_of(rel, declaration)
    rows = []
    pending: list[str] = []
    for offset, line in enumerate(body):
        doc = DOC_RE.match(line)
        if doc:
            pending.append(doc.group(1).strip())
            continue
        if not line.strip() or line.strip().startswith("//"):
            continue
        match = VARIANT_RE.match(line)
        if match:
            rows.append(
                {
                    "name": match.group(1),
                    "payload": (match.group(2) or "").strip() or "-",
                    "doc": " ".join(pending).strip() or "-",
                    "line": first_line + offset,
                }
            )
        pending = []
    return rows


def struct_names(rel: str) -> list[str]:
    return [
        match.group(1)
        for match in re.finditer(
            r"^pub const ([A-Z][A-Za-z0-9]*) = struct \{", "\n".join(read(rel)), re.M
        )
    ]


def table(header: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    for row in rows:
        out.append("| " + " | ".join(cell(value) for value in row) + " |")
    return "\n".join(out) + "\n"


def config_page() -> str:
    src = "src/server/config.zig"
    lines = read(src)
    text = "\n".join(lines)
    out = [BANNER, "# Config Catalog\n"]
    out.append(
        "Every operator-facing tunable, parsed from its declaration. Semantics live in\n"
        "[GAME_OPTIONS.md](../GAME_OPTIONS.md), [RULES_CONFIG.md](../RULES_CONFIG.md) and\n"
        "[subsystems/config.md](../subsystems/config.md); this page is the lookup table.\n"
    )

    match = re.search(r"known_serverconfig_names = \[_\]\[\]const u8\{(.*?)\n\};", text, re.S)
    names = re.findall(r'"([^"]+)"', match.group(1)) if match else []
    array_line = text[: match.start()].count("\n") + 1 if match else 0
    rows = []
    for name in names:
        prop_lines = [
            index + 1 for index, line in enumerate(lines) if f'prop(raw, "{name}")' in line
        ]
        destination = "-"
        if prop_lines:
            window = "\n".join(lines[prop_lines[0] - 1 : prop_lines[0] + 9])
            assign = re.search(r"\b(?:cfg|stats|self)\.([a-z_][a-z0-9_]*)\s*=", window)
            if assign:
                destination = assign.group(1)
        rows.append([f"`{name}`", destination, src, str(prop_lines[0] if prop_lines else array_line)])
    out.append("## serverconfig.xml keys\n")
    out.append(
        f"`known_serverconfig_names` ({src}:{array_line}) is the accepted key list; the\n"
        "destination column names the field the parser assigns.\n"
    )
    out.append(table(["Key", "Destination field", "Parsed in", "Line"], rows))

    out.append("\n## zdtd.toml\n")
    sections = [s for s in fields_of("src/server/zdtd_config.zig", "File") if "*" not in s["type"]]
    out.append(
        "The root `File` struct (`src/server/zdtd_config.zig:294`) names the sections; each\n"
        "section struct names the fields `util/toml_bind.zig` binds, so a new field needs no\n"
        "parser change (ADR 0021). Pointer fields (an arena handle) are not operator settings\n"
        "and are not listed.\n"
    )
    for section in sections:
        group = section["type"].split("=")[0].strip()
        rows = [
            [f"`{field['name']}`", f"`{field['type']}`", f"`{field['default']}`", str(field["line"])]
            for field in fields_of("src/server/zdtd_config.zig", group)
        ]
        out.append(f"\n### `[{section['name']}]` ({group}, `src/server/zdtd_config.zig:{section['line']}`)\n")
        out.append(table(["Field", "Type", "Default", "Line"], rows) if rows else "No fields parsed.\n")

    rules = "src/ecs/rules.zig"
    out.append("\n## Sim rule groups\n")
    out.append(
        "`Rules` (`src/ecs/rules.zig`) is the sim parameter table a preset pack or\n"
        "`zdtd.toml` overlays; a value is a floor where stock ships per-entity data\n"
        "(ADR 0021).\n"
    )
    for group in fields_of(rules, "Rules"):
        group_type = re.sub(r"\s*=.*", "", group["type"]).strip()
        rows = [
            [f"`{field['name']}`", f"`{field['type']}`", f"`{field['default']}`", str(field["line"])]
            for field in fields_of(rules, group_type)
        ]
        out.append(f"\n### `rules.{group['name']}` (`{group_type}`, `{rules}:{group['line']}`)\n")
        out.append(table(["Field", "Type", "Default", "Line"], rows) if rows else "No fields parsed.\n")
    return "\n".join(out).rstrip() + "\n"


def admin_page() -> str:
    admin = "src/server/admin.zig"
    out = [BANNER, "# Admin and Console Verbs\n"]
    out.append(
        "Every verb surface the server accepts, parsed from its declaration. Wire and\n"
        "permission semantics live on [subsystems/admin.md](../subsystems/admin.md).\n"
    )
    for declaration in ("Command", "BanSub", "AdminSub", "WhitelistSub"):
        rows = [
            [f"`{variant['name']}`", f"`{variant['payload']}`", str(variant["line"]), variant["doc"]]
            for variant in variants_of(admin, declaration)
        ]
        out.append(f"\n## `{declaration}` (`{admin}`)\n")
        out.append(
            table(["Variant", "Payload", "Line", "Summary"], rows)
            if rows
            else "No variants parsed.\n"
        )

    console = "src/server/admin_console.zig"
    text = "\n".join(read(console))
    verbs = []
    for match in re.finditer(r"eqAny\(verb, &\.\{(.*?)\}\)", text, re.S):
        line = text[: match.start()].count("\n") + 1
        names = re.findall(r'"([^"]+)"', match.group(1))
        verbs.append([", ".join(f"`{name}`" for name in names), str(line)])
    out.append(f"\n## Console verbs dispatched in process (`{console}`)\n")
    out.append(
        "Verbs handled by `handleConsoleCmd` and its F1 player-console path; aliases are\n"
        "grouped as the dispatcher groups them. Anything else routes through the `Command`\n"
        "union above.\n"
    )
    out.append(table(["Verbs (aliases grouped)", "Line"], verbs) if verbs else "None parsed.\n")

    text_zig = "src/server/c2s_text.zig"
    text = "\n".join(read(text_zig))
    anchor = text.find("const player_console_allowlist")
    allow = []
    if anchor >= 0:
        window = text[anchor : anchor + 2000]
        block = re.search(r"\{([^{}]*)\}", window, re.S)
        if block:
            base = text[: anchor + block.start()].count("\n") + 1
            for offset, line in enumerate(block.group(1).splitlines()):
                for name in re.findall(r'"([^"]+)"', line):
                    allow.append([f"`{name}`", str(base + offset)])
    out.append(f"\n## Player console allowlist (`{text_zig}`)\n")
    out.append(
        "The verbs an unprivileged in-game console may run; every other verb needs a\n"
        "permission level (`src/server/admin_console.zig:307`).\n"
    )
    out.append(table(["Verb", "Line"], allow) if allow else "None parsed.\n")

    bot = "src/server/game/bot.zig"
    content = "\n".join(read(bot))
    bot_rows = []
    for match in re.finditer(r'std\.mem\.eql\(u8, sub, "([a-z_]+)"\)', content):
        bot_rows.append([f"`bot {match.group(1)}`", str(content[: match.start()].count("\n") + 1)])
    out.append(f"\n## Bot verbs (`{bot}`)\n")
    out.append("Subcommands of the `bot` admin verb handled by the host servant.\n")
    out.append(table(["Verb", "Line"], bot_rows) if bot_rows else "None parsed.\n")

    out.append("\n## Plugin host verbs (`src/plugin/wasm.zig`)\n")
    host_rows = []
    for file in ("src/plugin/wasm.zig",):
        content = "\n".join(read(file))
        for match in re.finditer(r'linker\.defineFuncCtx\("zdtd", "([a-z_]+)"', content):
            host_rows.append(
                [f"`zdtd.{match.group(1)}`", file, str(content[: match.start()].count("\n") + 1)]
            )
    out.append(table(["Import", "Defined in", "Line"], host_rows) if host_rows else "None parsed.\n")
    return "\n".join(out).rstrip() + "\n"


def save_page() -> str:
    out = [BANNER, "# Save Formats\n"]
    out.append(
        "Upper-case format magics found in the persistence paths, each with the function\n"
        "that reads or writes it. The scan lists literals, so a magic that only appears in a\n"
        "test is filtered by the generator's denylist; durable-versus-memory-only is stated\n"
        "on [subsystems/persistence.md](../subsystems/persistence.md) and\n"
        "[subsystems/world-store.md](../subsystems/world-store.md).\n"
    )
    rows = []
    for rel in SAVE_SCAN:
        lines = read(rel)
        enclosing = ""
        for index, line in enumerate(lines):
            fn = re.match(r"^(?:pub )?fn ([A-Za-z0-9_]+)", line)
            if fn:
                enclosing = fn.group(1)
            for literal in re.findall(r'"([A-Z][A-Z0-9]{2,7})"', line):
                if literal in MAGIC_DENYLIST:
                    continue
                doc_lines = []
                back = index - 1
                while back >= 0:
                    match = DOC_RE.match(lines[back])
                    if not match:
                        break
                    doc_lines.append(match.group(1).strip())
                    back -= 1
                doc = " ".join(reversed(doc_lines)).strip()[:120] or "-"
                rows.append([f"`{literal}`", rel, str(index + 1), enclosing or "-", doc])
    rows.sort(key=lambda row: (row[1], int(row[2])))
    out.append(table(["Magic", "File", "Line", "Enclosing function", "Nearby doc"], rows))
    return "\n".join(out).rstrip() + "\n"


def module_page() -> str:
    out = [BANNER, "# Module Graph\n"]
    out.append(
        "Package dependency edges that exist in `src/`, next to the edges\n"
        "`scripts/lint-architecture.sh` enforces. A row counts real `@import` occurrences,\n"
        "not intent.\n"
    )
    counts: dict[tuple[str, str], int] = {}
    import_re = re.compile(r'@import\("(?:\.\./)+([a-z_]+)/')
    for path in sorted((ROOT / "src").rglob("*.zig")):
        rel = path.relative_to(ROOT)
        parts = rel.parts
        if len(parts) < 3:
            continue
        source = parts[1]
        for match in import_re.finditer(path.read_text(encoding="utf-8", errors="replace")):
            target = match.group(1)
            # `../game/net.zig` from src/server/* names the src/server/game
            # subpackage, so resolve against the source package before the root.
            if not (ROOT / "src" / target).is_dir():
                if (ROOT / "src" / source / target).is_dir():
                    target = f"{source}/{target}"
                else:
                    continue
            counts[(source, target)] = counts.get((source, target), 0) + 1
    rows = [
        [f"`{source}`", f"`{target}`", str(count)]
        for (source, target), count in sorted(counts.items())
    ]
    out.append("## Observed edges\n")
    out.append(
        "Only imports of another package directory are counted; single-file imports\n"
        "(`../protocol.zig`) and std imports are not edges between packages.\n"
    )
    out.append(table(["From package", "To package", "Imports"], rows) if rows else "None parsed.\n")

    out.append("\n## Enforced edges (`scripts/lint-architecture.sh`)\n")
    script = "\n".join(read("scripts/lint-architecture.sh"))
    enforced = []
    for match in re.finditer(r"^check_edges (\w+) '([^']+)'", script, re.M):
        enforced.append([f"`{match.group(1)}`", f"`{match.group(2)}` (forbidden)"])
    out.append(table(["Package", "Rule"], enforced) if enforced else "None parsed.\n")

    out.append("\n## Graph\n")
    out.append("```mermaid")
    out.append("graph LR")
    for source, target in sorted(counts):
        out.append(f"  {source} --> {target}")
    out.append("```")
    return "\n".join(out).rstrip() + "\n"


PAGES = {
    "config.md": config_page,
    "admin-verbs.md": admin_page,
    "save-formats.md": save_page,
    "module-graph.md": module_page,
}


def main() -> int:
    check = "--check" in sys.argv[1:]
    stale = []
    for name, builder in PAGES.items():
        path = OUT / name
        rendered = builder()
        if check:
            current = path.read_text(encoding="utf-8") if path.is_file() else None
            if current != rendered:
                stale.append(str(path.relative_to(ROOT)))
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered, encoding="utf-8")
        print(f"gen_docs_catalogs: wrote {path.relative_to(ROOT)}")
    if check and stale:
        for name in stale:
            print(f"gen_docs_catalogs: stale {name}", file=sys.stderr)
        print(
            "gen_docs_catalogs: run `make docs-catalogs` and commit the regenerated pages",
            file=sys.stderr,
        )
        return 1
    if check:
        print("gen_docs_catalogs: ok (4 pages fresh)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
